# Generated by Django 5.2.13 on 2026-04-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255, verbose_name='Адрес клиента')),
                ('status', models.CharField(max_length=255, verbose_name='Статус заказа')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время подачи заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время смены статуса заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена услуги')),
            ],
        ),
        migrations.CreateModel(
            name='RequestPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(verbose_name='Url картинки')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Время загрузки фото')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='met.request', verbose_name='Id запроса')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за кг')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления цен')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='met.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Request_services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='met.request', verbose_name='ID запроса')),
                ('services_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='met.service', verbose_name='ID услуги')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Номер телефона')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Пароль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания пользователя')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления пользователя')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='met.role', verbose_name='Роль')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='met.user'),
        ),
    ]
