# Generated by Django 5.2.13 on 2026-04-25 20:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('met', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='request_services',
            options={'verbose_name': 'Услуга в заявке', 'verbose_name_plural': 'Услуги в заявке'},
        ),
        migrations.AlterModelOptions(
            name='requestphoto',
            options={'verbose_name': 'Фото к заявке', 'verbose_name_plural': 'Фото к заявкам'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='scraptype',
            options={'verbose_name': 'Тип металла', 'verbose_name_plural': 'Типы металла'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время подачи заявки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=255, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='met.user', verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='requestphoto',
            name='image_url',
            field=models.ImageField(upload_to='photos/', verbose_name='Загрузка картинки'),
        ),
    ]
