# Generated by Django 5.2.13 on 2026-06-01 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('met', '0002_alter_category_options_alter_request_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestphoto',
            name='image_url',
        ),
        migrations.AddField(
            model_name='requestphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото лома'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='met.user', verbose_name='ID пользователя'),
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес в кг')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='met.request')),
                ('scrap_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='met.scraptype')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='scrap_types',
            field=models.ManyToManyField(through='met.RequestItem', to='met.scraptype', verbose_name='Компоненты лома'),
        ),
    ]
