# Generated by Django 5.2.13 on 2026-08-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('met', '0003_remove_requestphoto_image_url_requestphoto_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='requestphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки фото'),
        ),
    ]
