# Generated by Django 5.2.13 on 2026-08-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('met', '0004_alter_request_total_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='act_document',
            field=models.FileField(blank=True, null=True, upload_to='acts/', verbose_name='Акт приёма-передачи'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='reference_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на прайс-лист поставщика'),
        ),
    ]
