# Generated by Django 5.2.13 on 2026-08-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('met', '0005_request_act_document_requestitem_reference_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestitem',
            name='reference_url',
        ),
        migrations.AddField(
            model_name='scraptype',
            name='reference_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на прайс-лист поставщика'),
        ),
    ]
